# Generated by Django 5.2.8 on 2026-02-26 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="category",
            table="categories",
        ),
    ]
