# Generated by Django 5.2.8 on 2026-02-27 16:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_category_table"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name_plural": "Categories"},
        ),
        migrations.AddField(
            model_name="claim",
            name="claim_image",
            field=models.ImageField(blank=True, null=True, upload_to="claim_images/"),
        ),
        migrations.AddField(
            model_name="claim",
            name="confidence_score",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="item",
            name="embedding_vector",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="item",
            name="event_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="trust_score",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="claim",
            name="claimer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="claims",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="status",
            field=models.CharField(
                choices=[
                    ("OPEN", "Open"),
                    ("CLAIMED", "Claimed"),
                    ("CLOSED", "Closed"),
                    ("REPORTED", "Reported"),
                ],
                default="OPEN",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="claim",
            unique_together={("item", "claimer")},
        ),
        migrations.AddIndex(
            model_name="item",
            index=models.Index(
                fields=["item_type"], name="core_item_item_ty_e3aaee_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="item",
            index=models.Index(fields=["status"], name="core_item_status_afb428_idx"),
        ),
        migrations.AddIndex(
            model_name="item",
            index=models.Index(
                fields=["category"], name="core_item_categor_72af40_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="item",
            index=models.Index(
                fields=["date_posted"], name="core_item_date_po_b5aa48_idx"
            ),
        ),
    ]
