# Generated by Django 5.2.8 on 2026-03-02 15:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_category_options_claim_claim_image_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="claim",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "APPROVED")),
                fields=("item",),
                name="unique_approved_claim_per_item",
            ),
        ),
    ]
