# Generated by Django 5.2.8 on 2026-03-02 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_claim_unique_approved_claim_per_item"),
        ("core", "0005_add_categories"),
    ]

    operations = []
