# Generated by Django 5.2.8 on 2026-04-16 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_notification"),
    ]

    operations = [
        migrations.RenameField(
            model_name="item",
            old_name="embedding_vector",
            new_name="image_embedding",
        ),
        migrations.AddField(
            model_name="item",
            name="text_embedding",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
