# Generated by Django 5.2.8 on 2026-04-30 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_rename_embedding_vector_item_image_embedding_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('cv_score', models.FloatField(blank=True, null=True)),
                ('nlp_score', models.FloatField(blank=True, null=True)),
                ('category_boost', models.FloatField(default=0)),
                ('location_boost', models.FloatField(default=0)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('matched_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_matches', to='core.item')),
                ('source_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_matches', to='core.item')),
            ],
            options={
                'ordering': ['-score'],
                'unique_together': {('source_item', 'matched_item')},
            },
        ),
    ]
