# Generated by Django 5.2.8 on 2026-04-30 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_itemmatch'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemmatch',
            name='user_feedback',
            field=models.CharField(blank=True, choices=[('HELPFUL', 'Helpful'), ('NOT_HELPFUL', 'Not Helpful'), ('IGNORED', 'Ignored')], max_length=20, null=True),
        ),
    ]
