# Generated by Django 5.2.8 on 2026-05-08 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_itemmatch_user_feedback"),
    ]

    operations = [
        migrations.AddField(
            model_name="itemmatch",
            name="category_match",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="itemmatch",
            name="location_match",
            field=models.BooleanField(default=False),
        ),
    ]
